name: 'Destroy nomad cluster'
description: 'Destroy the nomad cluster used to test nf-nomad against'
inputs:
  CLIENT_ID:
    description: 'The Azure Active Directory (AAD) client ID for authentication.'
    required: true
  SUBSCRIPTION_ID:
    description: 'The Azure subscription ID where the resources will be managed.'
    required: true
  TENANT_ID:
    description: 'The Azure Active Directory (AAD) tenant ID for authentication.'
    required: true
  CLIENT_SECRET:
    description: 'The client secret associated with the Azure Active Directory (AAD) client ID.'
    required: true
  RESOURCE_GROUP_NAME:
    description: "The name of the resource group."
    required: true
  STORAGE_ACCOUNT_NAME:
    description: "The name of the storage account."
    required: true
  IMAGE_NAME:
    description: "The Azure image to use for the server and client machines."
    required: true
  NOMAD_ACL_ENABLED:
    description: "Enable nomad ACL."
    required: true
  CONSUL_ACL_ENABLED:
    description: "Enable consul ACL."
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Initialize terraforms
      shell: bash
      working-directory: ./terraform
      run: terraform init -reconfigure
      env:
        ARM_CLIENT_ID: ${{ inputs.CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ inputs.TENANT_ID }}
        ARM_CLIENT_SECRET: ${{ inputs.CLIENT_SECRET }}

    - name: Destroy resources
      shell: bash
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ inputs.CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ inputs.TENANT_ID }}
        ARM_CLIENT_SECRET: ${{ inputs.CLIENT_SECRET }}
        TF_VAR_client_id: ${{ inputs.CLIENT_ID }}
        TF_VAR_subscription_id: ${{ inputs.SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ inputs.TENANT_ID }}
        TF_VAR_client_secret: ${{ inputs.CLIENT_SECRET }}
        TF_VAR_resource_group_name: ${{ inputs.RESOURCE_GROUP_NAME }}
        TF_VAR_storage_account_name: ${{ inputs.STORAGE_ACCOUNT_NAME }}
        TF_VAR_image_name: ${{ inputs.IMAGE_NAME }}
        TF_VAR_nomad_acl_enabled: ${{ inputs.NOMAD_ACL_ENABLED }}
        TF_VAR_consul_acl_enabled: ${{ inputs.CONSUL_ACL_ENABLED }}
      run: terraform destroy -auto-approve