name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        java_version: [19]

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java_version}}
          architecture: x64

      - name: Tests
        run: ./gradlew check
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          architecture: x64
      - name: version
        run: echo "::set-output name=version::$(./gradlew properties -q | awk '/^version:/ {print $2}')"
        id: version

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: build artifacts
        run: ./gradlew jsonPlugin

      - name: Upload artifact and release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./plugins/nf-nomad/build/plugin/*