name: test
on:
  push

jobs:
  test:
    name: Test
    runs-on: self-hosted
    concurrency:
      group: example-group
      cancel-in-progress: true
    
    steps:
      - name: Print
        run: echo 'OK'