name: test
on:
  push

jobs:
  test:
    name: Test
    runs-on: self-hosted
    concurrency:
      group: example-group
      cancel-in-progress: true
    
    steps:
      - name: Print
        run: echo 'OK'
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Create nomad
        uses: ./.github/actions/create_nomad_cluster
        with:
          CLIENT_ID: ${{ secrets.TF_VAR_CLIENT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
          TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID }}
          CLIENT_SECRET: ${{ secrets.TF_VAR_CLIENT_SECRET }}
